version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT:-18481}:80"
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./htpasswd:/etc/nginx/htpasswd
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - doocs_md
    networks:
      - doocs_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  doocs_md:
    image: doocs/md:latest
    container_name: doocs_md
    networks:
      - doocs_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  doocs_network:
    driver: bridge

volumes:
  doocs_data:
    driver: local 